development:
  songkick_api_key: "Wa5KXVW2sx3ysyPy"
  echonest_api_key: "BAY8T6EZ4GBPAZJOE"
  echonest_consumer_key: "efa98b18c0fb9526f89c9c2cfe7eaa05"
  echonest_shared_secret: "KwNoA7DHTnWkaS091Nscwg"
production:
  songkick_api_key: "Wa5KXVW2sx3ysyPy"
  echonest_api_key: "BAY8T6EZ4GBPAZJOE"
  echonest_consumer_key: "efa98b18c0fb9526f89c9c2cfe7eaa05"
  echonest_shared_secret: "KwNoA7DHTnWkaS091Nscwg"
